version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - neatline_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  omeka-s:
    depends_on:
      - db
    image: jeremyboggs/omeka-s
    volumes:
      - ./neatline_plugins:/var/www/html/modules/
    ports:
      - "9000:80"
    restart: always
      
volumes:
  neatline_db_data:
  neatline_plugins:
