version: '2'

services:
  omekaS_test_db:
    image: mysql:5.7
    container_name: omekaS_test_db
    volumes:
      - ./neatline_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  omekaS_test:
    depends_on:
      - omekaS_test_db
    image: scholarslab/omeka-s
    container_name: omekaS_test
    volumes:
      - ./neatline_plugins/Neatline:/var/www/html/modules/Neatline
      - ./database.ini:/var/www/html/config/database.ini
    environment:
      OMEKA_DB_HOST: ${OMEKA_DB_HOST}
      OMEKA_DB_USER: ${MYSQL_USER}
      OMEKA_DB_PASSWORD: ${MYSQL_PASSWORD}
      OMEKA_TABLE_PREFIX: ${OMEKA_TABLE_PREFIX}
    ports:
      - "9000:80"
    restart: always
      
